config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/destroy'
  devise_for :users
  root to: "rocks#index"
  get '/dashboard', to: "pages#dashboard"

  resources :rocks, only: [:show, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:destroy] do
    member do
      patch :accept, :decline
    end
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/partials/_banner.html.erb
<div class="banner">
  <div class="banner-text">
    <h1>Rock Rental</h1>
    <p>Rock Your World, One Rental at a Time<p>
  </div>
</div>

app/views/partials/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div class="footer d-flex align-content-space-between sticky-bottom">
  <div class="footer-the-rock">
    <%= link_to "https://www.youtube.com/watch?v=C-9_lRn5yM0>", target: "_blank" do %>
      <img src="https://res.cloudinary.com/di8qjnwgb/image/upload/v1699067069/minitherock2_srctmn.png", style="width: 30px";>
    <% end %>
  </div>
  <div class="footer-links">
    <a href="#">RockRental</a>
  </div>
  <div class="footer-copyright">
    this page was made with love.... our insatiable love for rocks
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "RockRental", root_path, class: "navbar-brand ms-3" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <div class="ms-auto">
          <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>