config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/destroy'
  devise_for :users
  root to: "rocks#index"
  get '/dashboard', to: "pages#dashboard"

  resources :rocks, only: [:show, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:destroy] do
    member do
      patch :accept, :decline
    end
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rock
  belongs_to :user
  has_one :review, dependent: :destroy

  validates :start_time, :end_time, presence: true

  def self.upcoming_bookings_for_user(user)
    Booking.where('start_time > ? AND user_id = ?', Time.now, user.id)
  end

  def total_price
    daily_price = Rock.find(self.rock_id).daily_price
    price = daily_price * ((self.end_time - self.start_time) / (24 * 60 * 60 ))
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_rock, only: [:new, :create, :show]
  before_action :set_booking, only: [:accept, :decline, :destroy, :show]


  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.rock = @rock
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      flash[:alert] = "Please enter start and end dates"
      redirect_to rock_bookings_path
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def accept
    if @booking.update(status: 'accepted')
      redirect_to dashboard_path, notice: 'Booking accepted'
    else
      redirect_to dashboard_path, alert: 'Failed to accept booking'
    end
  end

  def decline
    if @booking.update(status: 'declined')
      redirect_to dashboard_path, notice: 'Booking declined'
    else
      redirect_to dashboard_path, alert: 'Failed to decline booking'
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :rock_id, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_rock
    @rock = Rock.find(params[:rock_id])
  end
end

app/views/bookings/new.html.erb
<div class="bookings-container my-5">
  <div class="d-flex justify-content-center">
    <h1> Reserve your dream Rock now! </h1>
  </div>
  <div class="bookings-spacing d-flex justify-content-around align-items-center my-5">
    <div class="card custom-card shadow" style="border: 2px solid #F148FB;">
      <%= cl_image_tag(@rock.photo.key, alt: "Shows a photo of the rock for rent", style: "height: 350px; object-fit: cover;") %>
      <div class="m-5">
        <h1> <%= @rock.rock_type %> </h1>
        <p>Description: <%= @rock.description %></p>
      </div>
    </div>
    <div class="select-dates" data-controller="price-calculator">
      <h2>Select your dates</h2>
    <%= simple_form_for [@rock, @booking] do |f| %>
            <%= f.input :start_time, as: :string, input_html: { data: { controller: "datepicker",
                                                                        action: "change->price-calculator#updatePrice",
                                                                        price_calculator_target: "startTime" } } %>

            <%= f.input :end_time, as: :string, input_html: { data: { controller: "datepicker",
                                                                      action: "change->price-calculator#updatePrice",
                                                                      price_calculator_target: "endTime" } } %>
      <div id="price-container">
            <p><span data-price-calculator-target="price" data-daily-price="<%= @rock.daily_price %>"></span></p>
      </div>
        <%= f.submit "Request Booking", class: "btn btn-primary" %>
      <% end %>
      <% if flash[:alert].present? %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
hi there
display the specific booking

<%= link_to "Write a Review", new_rock_booking_review_path(@rock, @booking), class: "btn btn-primary" %>