config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/destroy'
  devise_for :users
  root to: "rocks#index"
  get '/dashboard', to: "pages#dashboard"

  resources :rocks, only: [:show, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:destroy] do
    member do
      patch :accept, :decline
    end
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/dashboard.html.erb
<div class="dashboard-container m-5">
  <h2> Hello, <%= @current_user.first_name.capitalize %> </h2>
  <% if @current_user.host %>
    <!--Add rock Button trigger modal -->
    <button type="button" class="btn btn-primary mb-5" data-bs-toggle="modal" data-bs-target="#addNewRock">
      Add a new rock!
    </button>


        <!-- Modal to add new rock -->
  <div class="modal fade" id="addNewRock" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addNewRockLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= simple_form_for(@rock) do |f| %>
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Add a new rock!</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
              <div class="modal-body">
                <%= f.input :rock_type %>
                <%= f.input :daily_price %>
                <%= f.input :description %>
                <%= f.input :photo, as: :file %>
              </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <%= f.submit "Add Rock", class: "btn btn-primary" %>
                </div>
            </div>
        <% end %>
    </div>
  </div>

    <div>
      <h3> My Rocks </h3>
      <div class="row gap-4">
        <% @current_user.rocks.each do |rock| %>
          <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-5" style="border: 2px solid #F148FB;">
            <div class="card">
              <%= cl_image_tag(rock.photo.key, alt:"Shows a photo of the rock for rent", style: "height: 350px; object-fit: contain;", class: "card-img-top") %>
            </div>

              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center m-2">
                  <div>
                    <h5 class="card-title flex-grow-1"><%= rock.rock_type %></h5>
                  </div>
                  <div>
                    <h5 class="card-title">$<%= rock.daily_price %>/day</h5>
                  </div>
                </div>
                  <p class="card-text" style="height: 50px; overflow: auto;"><%= rock.description %></p>
              </div>
              <!-- Modal to trigger edit form-->
              <div class="d-flex justify-content-end p-2 gap-3">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editRockModal-<%= rock.id %>">Edit</button>
                <%= link_to "Delete Rock", rock_path(rock), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
              </div>
              <!-- edit form-->
              <div class="modal fade" id="editRockModal-<%= rock.id %>" tabindex="-1" aria-labelledby="editRockModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="staticBackdropLabel">Edit</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                      <div class="modal-body">
                        <%= simple_form_for(rock) do |f| %>
                        <%= f.input :rock_type %>
                        <%= f.input :daily_price %>
                        <%= f.input :description %>
                        <%= f.input :photo, as: :file %>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><%= f.submit "Edit", class: "btn btn-primary" %></button>
                        </div>
                      </div>
                      <% end %>
                  </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>


  <!-- Current users bookings for their rocks -->
  <!-- TODO we need to sort where the below code fits in with the above -->
    <div class="mb-5">
      <h3>My Rock Bookings</h3>
      <% @my_bookings.each do |booking| %>
        <% if @current_user.rocks.include?(booking.rock) && booking.status == 'pending' %>
          <div class="m-2 d-flex justify-content-between align-items-center w-50" style="border: 2px solid #F148FB;">
            <div>
              <h5> Rock: <%= booking.rock.rock_type %> </h5>
              <p> Start time: <%= booking.start_time.strftime("%D") %> </p>
              <p> End time: <%= booking.end_time.strftime("%D") %> </p>
              <p> Total Price: $<%= booking.total_price %> </p>
              <p> Renter: <%= booking.user.first_name.capitalize %> </p>
            </div>
            <div class="d-flex flex-column">
              <div class="p-2">
                <%= link_to "Accept Booking", accept_booking_path(booking), class:"btn btn-success", data: {turbo_method: :patch} %>
              </div>
              <div class="p-2">
                <%= link_to "Decline Booking", decline_booking_path(booking), class:"btn btn-warning", data: {turbo_method: :patch} %>
              </div>
            </div>
        <% elsif @current_user.rocks.include?(booking.rock) && booking.status == 'accepted' %>
          <div class="m-2 d-flex justify-content-between align-items-center w-50" style="border: 2px solid #F148FB;">
            <div>
              <h5>Rock: <%= booking.rock.rock_type %></h5>
              <p> Start time: <%= booking.start_time.strftime("%D") %> </p>
              <p> End time: <%= booking.end_time.strftime("%D") %> </p>
              <p> Total Price: $<%= booking.total_price %> </p>
              <p> Renter: <%= booking.user.first_name.capitalize %> </p>
            </div>
            <div class="d-flex flex-column">
              <div class="p-2">
                <% if (booking.end_time > Time.now) %>
                  <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                <% end %>
                <% if (booking.end_time < Time.now && booking.review.nil?) %>
                  <%= link_to "Write a Review", new_booking_review_path(booking), class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      <% end %>
    </div>



  <!--# Current users bookings -->
    <div>
      <h3>Upcoming Bookings</h3>
        <% if @upcoming_bookings_for_user.empty? %>
          <div>
            <p>You have no upcoming bookings!</p>
            <%= link_to "Make a booking", root_path %>
          </div>
        <% end %>

      <% @bookings.each do |booking| %>
        <% if booking.start_time > Time.now %>

          <div class="m-2 d-flex justify-content-between align-items-center w-50 p-3" style="border: 2px solid #F148FB;">
            <div>
              <h5> Rock: <%= booking.rock.rock_type %> </h5>
              <p> Start time: <%= booking.start_time.strftime("%D") %> </p>
              <p> End time: <%= booking.end_time.strftime("%D") %> </p>
              <p> Total Price: $<%= booking.total_price %> </p>
              <p> Owner: <%= booking.rock.user.email %> </p>
            </div>
            <div class="d-flex flex-column">
                <% if booking.status == 'pending' %>
                  <div class="p-2">
                    <p>You're request is pending... hold tight 🙀</p>
                  </div>
                  <div class="p-2">
                    <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  </div>
                <% elsif booking.status == 'declined' %>
                  <div class="p-2">
                    <p>Your request was declined. Try your luck agian next time! 😿</p>
                  </div>
                <% else %>
                  <div class="p-2">
                    <p>You're request has been approved!! 🪨</p>
                    <% if (booking.end_time > Time.now) %>
                      <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                    <% end %>
                  </div>
                <% end %>
                <% if (booking.end_time < Time.now && booking.review.nil?) %>
                  <div class="p-2">
                    <%= link_to "Write a Review", new_booking_review_path(booking), class: "btn btn-primary" %>
                  </div>
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div>
      <h3>Ongoing Bookings</h3>
      <% @bookings.each do |booking| %>
        <% if booking.start_time = Time.now %>
          <div class="m-2 d-flex justify-content-between align-items-center w-50 p-3" style="border: 2px solid #F148FB;">
            <div>
              <h5> Rock: <%= booking.rock.rock_type %> </h5>
              <p> Start time: <%= booking.start_time.strftime("%D") %> </p>
              <p> End time: <%= booking.end_time.strftime("%D") %> </p>
              <p> Owner: <%= booking.rock.user.email %> </p>
            </div>
            <div class="d-flex flex-column">
                <% if booking.status == 'pending' %>
                  <div class="p-2">
                    <p>You're request is pending... hold tight 🙀</p>
                  </div>
                  <div class="p-2">
                    <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  </div>
                <% elsif booking.status == 'declined' %>
                  <div class="p-2">
                    <p>Your request was declined. Try your luck agian next time! 😿</p>
                  </div>
                <% else %>
                  <div class="p-2">
                    <p>You're request has been approved!! 🪨</p>
                    <% if (booking.end_time > Time.now) %>
                      <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                    <% end %>
                  </div>
                <% end %>
                <% if (booking.end_time < Time.now && booking.review.nil?) %>
                  <div class="p-2">
                    <%= link_to "Write a Review", new_booking_review_path(booking), class: "btn btn-primary" %>
                  </div>
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>

    <div>
      <h3>Past Bookings</h3>
      <% @bookings.each do |booking| %>
        <% if booking.start_time < Time.now %>
          <div class="m-2 d-flex justify-content-between align-items-center w-50 p-3" style="border: 2px solid #F148FB;">
            <div>
              <h5> Rock: <%= booking.rock.rock_type %> </h5>
              <p> Start time: <%= booking.start_time.strftime("%D") %> </p>
              <p> End time: <%= booking.end_time.strftime("%D") %> </p>
              <p> Owner: <%= booking.rock.user.email %> </p>
            </div>
            <div class="d-flex flex-column">
                <% if booking.status == 'pending' %>
                  <div class="p-2">
                    <p>You're request is pending... hold tight 🙀</p>
                  </div>
                  <div class="p-2">
                    <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  </div>
                <% elsif booking.status == 'declined' %>
                  <div class="p-2">
                    <p>Your request was declined. Try your luck agian next time! 😿</p>
                  </div>
                <% else %>
                  <div class="p-2">
                    <p>You're request has been approved!! 🪨</p>
                    <% if (booking.end_time > Time.now) %>
                      <%= link_to "Cancel Booking", booking_path(booking), class:"btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                    <% end %>
                  </div>
                <% end %>
                <% if (booking.end_time < Time.now && booking.review.nil?) %>
                  <div class="p-2">
                    <%= link_to "Write a Review", new_booking_review_path(booking), class: "btn btn-primary" %>
                  </div>
                <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h4>HI ALEX
</h4>