config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/destroy'
  devise_for :users
  root to: "rocks#index"
  get '/dashboard', to: "pages#dashboard"

  resources :rocks, only: [:show, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:destroy] do
    member do
      patch :accept, :decline
    end
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/rock.rb
class Rock < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :rock_type, :daily_price, :description, presence: true
end

app/controllers/rocks_controller.rb
class RocksController < ApplicationController
  before_action :set_rock, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @rocks = Rock.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @rock = Rock.new
  end

  def create
    @rock = Rock.new(rock_params)
    @rock.user = current_user
    if @rock.save
      redirect_to rock_path(@rock)
    else
      render "pages/dashboard", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @rock.update(rock_params)
    redirect_to dashboard_path
  end

  def destroy
    @rock = set_rock
    @rock.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def rock_params
    params.require(:rock).permit(:rock_type, :daily_price, :description, :photo)
  end

  def set_rock
    @rock = Rock.find(params[:id])
  end
end

app/views/rocks/edit.html.erb
<h1>Edit a rock</h1>
<%= form_with model: @rock do |f| %>
  <%= f.label :rock_type %>
  <%= f.text_field :rock_type %>
  <%= f.label :daily_price %>
  <%= f.text_field :daily_price %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/rocks/index.html.erb
<div>
<%= render 'partials/banner' %>
</div>

<div class="card-container m-5">
  <div class="row gap-3 justify-content-evenly">
    <% @rocks.each do |rock| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-5" style="border: 2px solid #F148FB;">
        <div class="card custom-card shadow">
          <%= cl_image_tag(rock.photo.key, alt:"Shows a photo of the rock for rent", style: "height: 350px; object-fit: contain;") %>
        </div>
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center m-2">
            <div>
              <h5 class="card-title flex-grow-1"><%= rock.rock_type %></h5>
            </div>
            <div>
              <h5 class="card-title">$<%= rock.daily_price %>/day</h5>
            </div>
          </div>
          <p class="card-text" style="height: 50px; overflow: auto;"><%= rock.description %></p>
          <div class="card-footer text-muted my-2">
            <%= link_to "See more", rock_path(rock), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rocks/show.html.erb
<div class="show-page-container m-5">
  <div class="d-flex justify-content-between align-items-start show-page-card">
    <div class="card custom-card shadow" style="border: 2px solid #F148FB; flex: 1;">
      <%= cl_image_tag(@rock.photo.key, alt: "Shows a photo of the rock for rent", style: "height: 350px; object-fit: cover;") %>
      <div class="m-5">
        <h1><%= @rock.rock_type %></h1>
        <p>Description: <%= @rock.description %></p>
      </div>
    </div>
    <div class="ms-3 p-3" style="flex: 1;">
      <div class="booking-section">
        <h4>Daily Price: $<%= @rock.daily_price %></h4>

        <div>
          <button type="button" class="btn btn-primary mb-5" data-bs-toggle="modal" data-bs-target="#addNewBooking">
            Reserve your dream rock now!
          </button>
          <div class="modal fade" id="addNewBooking" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addNewBookingLabel" aria-hidden="true">
            <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h2>Select your dates</h2>
          </div>
          <div class="modal-body select-dates" data-controller="price-calculator">
          <%= simple_form_for [@rock, @booking] do |f| %>
            <%= f.input :start_time, as: :string, input_html: { data: { controller: "datepicker",
                                                                        action: "change->price-calculator#updatePrice",
                                                                        price_calculator_target: "startTime" } } %>
            <%= f.input :end_time, as: :string, input_html: { data: { controller: "datepicker",
                                                                      action: "change->price-calculator#updatePrice",
                                                                      price_calculator_target: "endTime" } } %>
          <div id="price-container">
                <p><span data-price-calculator-target="price" data-daily-price="<%= @rock.daily_price %>"></span></p>
          </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= f.submit "Request Booking", class: "btn btn-primary" %>
            </div>
          <% end %>
          <% if flash[:alert].present? %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
          <% end %>
        </div>
      </div>
          </div>
        </div>
      </div>
      <div class="mt-4 pt-4">
        <div class="reviews-container">
          <h4>Latest reviews</h4>
          <div class="reviews-cards">
            <% @rock.reviews.each do |review| %>
            <div class="review-card p-3" style="border: 0.5px solid #7122FA; mb-3 p-3">
              <% review.rating.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <div style="margin-top: 8px;">
                <p><%= review.content %></p>
                <p class="owner-name" style="font-size: 14px;"><i>by <%= review.booking.user.first_name %></i></p>
                <%# added logic to only see delete review button if you are the owner of the review %>
                <% if current_user && current_user.id == review.booking_id %>
                  <%= link_to "Delete", review_path(review), class: "btn btn-warning", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>